[project]
name = "image-hosting-app"
version = "0.1.0"
description = "Simple image hosting app behind nginx"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
]

[tool.uv]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=6.2.1",
]
